EBook.Admin/Controllers/Components/PagerViewComponent.cs
using eBook.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBook.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

EBook.Admin/Controllers/OrderController.cs
using eBook.AdminApp.Services;
using eBook.Data.Enums;
using eBook.ViewModels.Sales;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Threading.Tasks;

namespace eBook.AdminApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IOrderApiClient _orderApiClient;

        public OrderController(
            IConfiguration configuration,
            IOrderApiClient orderApiClient)
        {
            _configuration = configuration;
            _orderApiClient = orderApiClient;

        }
        // GET: OrderController
        public async Task<IActionResult> Index(Guid uId)
        {
            var result = await _orderApiClient.GetAll(uId);
            ViewBag.Status = Enum.GetValues(typeof(OrderStatus));
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(result.ResultObj);
        }

        // GET: OrderController/Detail/5
        public async Task<IActionResult> Detail(Guid id)
        {
            var result = await _orderApiClient.GetById(id);
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(result.ResultObj);
        }

        // GET: OrderController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _orderApiClient.GetById(id);
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(OrderStatus)));
            return View(result.ResultObj);
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, OrderStatus collection)
        {
            try
            {
                var result = await _orderApiClient.UpdateOrderStatus(id, collection);
                if (result.ResultObj)
                {
                    TempData["result"] = "Cập nhật trạng thái đơn hàng thành công";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var orderDelete = new OrderVm()
            {
                Id = id,
            };
            return View(orderDelete);
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OrderVm orderVm)
        {
            try
            {
                var result = await _orderApiClient.DeleteOrder(orderVm.Id);
                if (result.IsSuccessed)
                {
                    TempData["result"] = "Xóa đơn hàng thành công";
                    return RedirectToAction("Index");
                }
                return View(orderVm);

            }
            catch
            {
                return View();
            }
        }
    }
}

EBook.Admin/Views/Order/Delete.cshtml
@model eBook.ViewModels.Sales.OrderVm

@{
    ViewData["Title"] = "Xóa đơn hàng";
}
<style>
    .table {
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        row-gap: 20px;
    }

    .term {
        width: 20%;
        display: flex;
        align-items: center;
        padding: 8px 8px;
        background-color: #1d4adf85;
        color: white;
        position: relative;
    }

        .term::after {
            content: '';
            width: 12px;
            height: 24px;
            position: absolute;
            background-color: #1d4adf85;
            left: 100%;
            clip-path: polygon(0% 0%, 100% 50%, 0% 100%);
        }

    .desc {
        width: 80%;
        background-color: #eee;
        display: flex;
        align-items: center;
        padding: 8px 8px 8px 24px;
    }

    dd {
        margin-bottom: 0px;
    }
    /* ******************************* */

    * {
        box-sizing: border-box;
        margin: 0;
    }
</style>
<div class="container-fluid">
    <h1 class="mt-4">Xóa đơn hàng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item">Đơn hàng</li>

        <li class="breadcrumb-item active">Xóa đơn hàng</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Order">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="table">
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-outline-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

EBook.Admin/Views/Order/Index.cshtml
@model IEnumerable<eBook.ViewModels.Sales.OrderVm>
@using eBook.Utilities.Constants
@using Microsoft.AspNetCore.Http


@{
    ViewData["Title"] = "Danh sách đơn hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section Scripts{
    <script>
        
        setInterval(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
        const message = document.getElementById('mess-box');

        const token = "@Context.Session.GetString(SystemConstants.AppSettings.Token)";
        $(".status-check").change(function (event) {
         
            const orderId = $(this).attr('itemid');
            const orderStatus = $(this).attr('itemprop');
            
            
            const url = `https://localhost:5001/api/orders/${orderId}/${orderStatus}`;
            fetch(url, {
                method: 'PUT', headers: {
                    'Authorization': `Bearer ${token}`
                }
            })
                .then(response => {
                    if (response.ok) {
                        message.innerHTML = ` <div id="msgAlert" class="alert alert-success" role="alert">
                                                Cập nhật thành công
                                    </div>`
                    } else {

                    }
                })
                .catch(error => {   
                    console.log(error)
                    // Handle fetch error
                    // For example, display an error message or handle the error condition
                });
        });
       

    </script>
}
 <style>
            @@import 'https://fonts.googleapis.com/css?family=Roboto:100,300';
            @@import 'https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.2/css/simple-line-icons.min.css';
            @@import 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css';
            @@import 'https://fonts.googleapis.com/css?family=Roboto+Mono:300,700';
           
          
            h1 i {
                position: relative;
                font-size: 70px;
            }
            p {
                text-align: center;
                color: #fff;
                font-size: 14px;
                margin-bottom: 2em;
                line-height: 30px;
            }
            p img {
                position: relative;
                top: 8px;
                right: 10px;
            }
            .select2 {
                position: relative;
                overflow: hidden;
                display: block;
                height: 100%;
                border-bottom: 0px;
                border-radius: 3px;
                font-size: 12px;
                /*box-shadow: 0px 1em 2em -1.5em rgba(0, 0, 0, 0.5);*/
            }
            .select2 i.toggle {
                position: absolute;
                z-index: 4;
                right: 1.5em;
                top: 1.2em;
                color: #ccc;
            }
            .select2 .title,
            .select2 .placeholder {
                position: relative;
                display: block;
                width: 100%;
                height: 100%;
                padding: 0.9em 2em;
                background: rgba(255, 255, 255, 1);
                border-top: 1px solid rgba(0, 0, 0, 0.05);
                cursor: pointer;
            }
            .select2 > label > input {
                position: absolute;
                left: 0px;
                top: 0px;
                z-index: 2;
                width: 100%;
                height: 100%;
                display: block;
                opacity: 0;
                cursor: pointer;
            }
            .select2 > label > input:checked {
                z-index: 2;
            }
            .select2 > label > input:checked ~ i.toggle.icon-plus {
                display: none;
            }
            .select2 > label > input:checked ~ i.toggle.icon-minus {
                display: block;
            }
            .select2 > label > input:not(:checked) ~ i.toggle.icon-minus {
                display: none;
            }
            .select2 > label > input:not(:checked) ~ i.toggle.icon-plus {
                display: block;
            }
            .select2
                > label
                > input:not(:checked)
                ~ label.option
                input:not(:checked)
                ~ .title {
                display: none !important;
            }
            .select2 > label > input:disabled {
                cursor: no-drop;
            }
            .select2 label > span.placeholder {
                position: relative;
                z-index: 0;
                display: inline-block;
                width: 100%;
                color: #999;
                border-top: 0px;
            }
            .select2 label.option {
                display: block;
                overflow: hidden;
                z-index: 1;
                width: 100%;
                transition: all 1s ease-out;
            }
            .select2 label.option span.title {
                position: relative;
                z-index: 2;
                transition: background 0.3s ease-out;
            }
            .select2 label.option span.title i {
                padding-right: 8px;
                color: rgba(146, 168, 209, 1);
            }
            .select2 label.option span.title:hover {
                color: #fff;
                background: rgba(146, 168, 209, 0.5);
                box-shadow: inset 0px 1px 0px rgba(0, 0, 0, 0.1);
            }
            .select2 label.option input {
                display: none;
            }
            .select2 label.option input:checked ~ span.title {
                position: absolute;
                display: block;
                z-index: 1;
                top: 0px;
                font-size: 12px;
                background: #fff;
                border-top: 0px;
                box-shadow: none;
                color: inherit;
                width: 100%;
            }
            .select2 label.option input:disabled ~ span.title {
                background: #f9f9f9 !important;
                color: #aaa;
            }
            .select2 label.option input:disabled ~ span.title:hover {
                color: #aaa;
                background: none;
                cursor: no-drop;
            }
        </style>
        <div class="container-fluid">
            <h1 class="mt-4">Danh sách đơn hàng</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
                <li class="breadcrumb-item">Đơn hàng</li>
                <li class="breadcrumb-item active">Danh sách đơn hàng</li>
            </ol>
        <div class="card mb-12">
            <div class="card-header">
                <div class="row">
                    
                </div>
            </div>
            <div class="card-body" >
                <div class="row" id="mess-box">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table datatable table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">OrderDate</th>
                            <th scope="col">ShipName</th>
                            <th scope="col">PhoneNumber</th>
                            <th scope="col">ShipAddress</th>
                            <th scope="col">ShipEmail</th>
                            <th scope="col">TotalPrice</th>
                            <th scope="col">PaymentStatus</th>

                            <th scope="col">OrderStatus</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr class="table-row">
                                <td class="table-data" width="80px">
                                   
                                    @Html.DisplayFor(modelItem => item.Id )
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.OrderDate)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.ShipName)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.ShipPhoneNumber)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.ShipAddress)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.ShipEmail)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.TotalPrice)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.PaymentStatus)
                                </td>
                                <td class="table-data">
                                    
                                    <div class="select2 animated zoomIn">
                                        <label style="width: 164px">
                                            <input type="checkbox" name="placeholder" id="myinput"/>
                                            <i class="toggle icon icon-plus"></i>
                                            <i class="toggle icon icon-minus"></i>
                                            <span class="placeholder">
                                                <i class="bi bi-bag-check"></i>

                                                @Html.DisplayFor(modelItem => item.OrderStatus)
                                            </span>
                                  
                                                @foreach (var state in ViewBag.Status)
                                                {
                                                    <label class="option">
                                                        <input itemid="@item.Id" itemprop="@state" type="radio" class="status-check" name="option" />
                                                        <span class="title animated fadeIn">
                                                            @if (state.ToString() == "InProgress")
                                                            {
                                                                <i class="fa-solid fa-repeat"></i>
                                                            }
                                                            else if (state.ToString() == "Confirmed")
                                                            {
                                                                <i class="bi bi-bag-check"></i>

                                                            }
                                                            else if (state.ToString() == "Shipping")
                                                            {
                                                                <i class="fa-solid fa-truck-fast"></i>
                                                            }
                                                            else if (state.ToString() == "Canceled")
                                                            {
                                                                <i class="bi bi-bag-x"></i>
                                                            }
                                                            else if (state.ToString() == "Success")
                                                            {
                                                                <i class="fa-solid fa-money-bill-transfer"></i>
                                                            }

                                                            @state
                                                        </span>
                                                    </label>
                                                }
                                           
                                          
                                        </label>
                                    </div>
                                </td>
                                <td class="table-data">
                                    @Html.ActionLink("Details", "Detail", new { id = item.Id },new {@class = "btn btn-outline-info"})
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new {@class = "btn btn-outline-danger"})
                                </td>
                            </tr>
                        }

                    </tbody>
                    @*  @await Component.InvokeAsync("Pager", Model)*@
                </table>
            </div>
        </div>

    </div>

</div>