EBook.Admin/Controllers/Components/PagerViewComponent.cs
using eBook.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBook.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

EBook.Admin/Controllers/ProductController.cs
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using eBook.AdminApp.Hubs;
using eBook.AdminApp.Services;
using eBook.Utilities.Constants;
using eBook.ViewModels.Catalog.Categories;
using eBook.ViewModels.Catalog.Authors;
using eBook.ViewModels.Catalog.ProductImages;
using eBook.ViewModels.Catalog.Products;
using eBook.ViewModels.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using Newtonsoft.Json;

namespace eBook.AdminApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;
        private readonly IAuthorApiClient _authorApiClient;
        private readonly ICategoryApiClient _categoryApiClient;
        private IHubContext<ProductHub> _hubContext;

        public ProductController(IProductApiClient productApiClient,
            IConfiguration configuration,
            ICategoryApiClient categoryApiClient,
            IAuthorApiClient authorApiClient,
            IHubContext<ProductHub> hubContext)
        {
            _configuration = configuration;
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
            _authorApiClient = authorApiClient;
            _hubContext = hubContext;
        }

        public async Task<IActionResult> Index(string keyword, int[]? categoryId, int pageIndex = 1, int pageSize = 10)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId,
                CategoryIds = categoryId.ToList()
            };
            var data = await _productApiClient.GetPagings(request);
            //ViewBag.Keyword = keyword;

            //var categories = await _categoryApiClient.GetAll(languageId);
            //ViewBag.Categories = categories.ResultObj.Select(x => new SelectListItem()
            //{
            //    Text = x.Name,
            //    Value = x.Id.ToString(),
            //    Selected = categoryId.Contains(x.Id)
            //});
            //if (categoryId.Length > 0 && categoryId != null)
            //{
            //    var currentId = categories.ResultObj.FirstOrDefault(x => categoryId.ToList().Contains(x.Id)).Name;

            //    //ViewBag.CurrentCateId = currentId;
            //}
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var productCreateRequest = new ProductCreateRequest();

            var result = await _authorApiClient.GetAll();

            var categories = await _categoryApiClient.GetAll(languageId);

            foreach (var category in categories.ResultObj)
            {
                productCreateRequest.SelectCategories.Categories.Add(new SelectItem()
                {
                    Id = category.Id.ToString(),
                    Name = category.Name,
                    Selected = false
                });
            }
            return View(productCreateRequest);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create(ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.CreateProduct(request);
            if (result.IsSuccessed)
            {
                var resultCateAssign = await _productApiClient.CategoryAssign(result.ResultObj.Id, request.SelectCategories);
                if (!resultCateAssign.IsSuccessed)
                {
                    TempData["result"] = "KHông thêm được danh mục cho sản phảm mới";
                }
                TempData["result"] = result.Message;
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> CategoryAssign(int id)
        {
            var roleAssignRequest = await GetCategoryAssignRequest(id);
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> CategoryAssign(CategoryAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.CategoryAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var categoryAssignRequest = await GetCategoryAssignRequest(request.Id);

            return View(categoryAssignRequest);
        }

        private async Task<CategoryAssignRequest> GetCategoryAssignRequest(int id)
        {
            
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var productObj = await _productApiClient.GetById(id, languageId);
            var productCategory = productObj.ResultObj
                                            .ProductInCategories
                                            .Select(x => new CategoryVm()
                                            {
                                                Id = x.Category.Id,
                                                ParentId = x.Category.ParentId,
                                                Name = x.Category.CategoryTranslations
                                                                 .FirstOrDefault(x => x.LanguageId == languageId).Name,
                                            });
            var categories = await _categoryApiClient.GetAll(languageId);
            var categoryAssignRequest = new CategoryAssignRequest();
            foreach (var category in categories.ResultObj)
            {
                categoryAssignRequest.Categories.Add(new SelectItem()
                {
                    Id = category.Id.ToString(),
                    Name = category.Name,
                    Selected = productCategory.FirstOrDefault(x =>x.Id == category.Id) != null
                });
            }
            return categoryAssignRequest;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var product = _productApiClient.GetById(id, languageId).Result.ResultObj;
            var editVm = new ProductUpdateRequest()
            {
                Id = product.Id,
                Description = product.Description,
                Details = product.Details,
                Name = product.Name,
                SeoAlias = product.SeoAlias,
                SeoDescription = product.SeoDescription,
                SeoTitle = product.SeoTitle,
                Price = product.Price,
                Stock = product.Stock,
                OPrice = product.OriginalPrice
            };
            return View(editVm);
        }
      
        [HttpPost]
        //[Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] ProductUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.UpdateProduct(request);
            if (result)
            {
                TempData["result"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật sản phẩm thất bại");
            return View(request);
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var product = _productApiClient.GetById(id, languageId).Result.ResultObj;
            return View(product);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new ProductVm()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductVm request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.DeleteProduct(request.Id);
            if (result.ResultObj)
            {
                TempData["result"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddImage(int id)
        {
            ViewBag.ProductId = id;
            return View(new ProductImageCreateRequest());
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> AddImage(int id, ProductImageCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.AddImage(id, request);
            if (result)

EBook.Admin/Views/Product/AddImage.cshtml
@model eBook.ViewModels.Catalog.ProductImages.ProductImageCreateRequest

@{
    ViewData["Title"] = "AddImage";
}

    <div class="container-fluid">
        <h1 class="mt-4">Tạo mới hình ảnh</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
            <li class="breadcrumb-item">Danh sách sản phẩm</li>
            <li class="breadcrumb-item active">Thêm hình ảnh</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <a class="btn btn-outline-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
            </div>

            <div class="card-body">
                <div class="col-md-4">
                    <form asp-action="AddImage" enctype="multipart/form-data">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="row mb-3">
                        <label asp-for="Caption" class="col-sm-2 col-form-label">Caption</label>
                            <div class="col-sm-10">
                                <input asp-for="Caption" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="Caption" class="text-danger"></span>

                        </div>
                        <div class="row mb-3">
                        <div class="col-sm-10">
                            
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="gridCheck1" asp-for="IsDefault">
                                    <label class="form-check-label" for="gridCheck1" style="font-weight: 700;">
                                        IsDefault
                                    </label>
                                   
                                </div>
                            
                        </div>
                        </div>
                        <div class="row mb-3">

                            <label asp-for="SortOrder" class="col-sm-2 col-form-label">SortOrder</label>
                                <div class="col-sm-10">
                                    <input asp-for="SortOrder" type="number" class="form-control">
                                </div>
                                <span asp-validation-for="SortOrder" class="text-danger"></span>
                        </div>
                        
                     
                        <div class="row mb-3">
                            <label asp-for="ImageFile" class="col-sm-2 col-form-label">Image Upload</label>
                            <div class="col-sm-10">
                                <input asp-for="ImageFile" class="form-control" type="file" id="formFile" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Lưu lại" class="btn btn-outline-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

EBook.Admin/Views/Product/CategoryAssign.cshtml
@model eBook.ViewModels.Catalog.Products.CategoryAssignRequest

@{
    ViewData["Title"] = "Gán danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Thêm danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Gán danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">

             <form asp-action="CategoryAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row mb-3">
                        <legend class="col-form-label col-sm-2 pt-0">Select Categories</legend>
                    <div class="col-sm-10">
                        
                        <input type="hidden" asp-for="Id" />
                        @for (var i = 0; i < Model.Categories.Count; i++)
                        {
                            <div class="form-check">
                                <label class="form-check-label" for="gridCheck1">
                                    @Model.Categories[i].Name
                                </label>
                                    <input class="form-check-input" type="checkbox" id="gridCheck1" asp-for="Categories[i].Selected">

                                <input type="hidden" asp-for="Categories[i].Id" />
                                <input type="hidden" asp-for="Categories[i].Name" />
                            </div>

                        }
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Lưu lại" class="btn btn-outline-primary" />
                    </div>
                </form>
        </div>
    </div>
</div>
</div>

EBook.Admin/Views/Product/Delete.cshtml
@model eBook.ViewModels.Catalog.Products.ProductVm

@{
    ViewData["Title"] = "Xóa sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table {
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        row-gap: 20px;
    }

    .term {
        width: 20%;
        display: flex;
        align-items: center;
        padding: 8px 8px;
        background-color: #1d4adf85;
        color: white;
        position: relative;
    }

        .term::after {
            content: '';
            width: 12px;
            height: 24px;
            position: absolute;
            background-color: #1d4adf85;
            left: 100%;
            clip-path: polygon(0% 0%, 100% 50%, 0% 100%);
        }

    .desc {
        width: 80%;
        background-color: #eee;
        display: flex;
        align-items: center;
        padding: 8px 8px 8px 24px;
    }

    dd {
        margin-bottom: 0px;
    }
    /* ******************************* */

    * {
        box-sizing: border-box;
        margin: 0;
    }
</style>
<div class="container-fluid">
    <h1 class="mt-4">Xóa sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>

        <li class="breadcrumb-item active">Xóa sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="table">
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-outline-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

EBook.Admin/Views/Product/DeleteImage.cshtml
@using eBook.ViewModels.Catalog.ProductImages
@model System.Linq.IOrderedEnumerable<ProductImageVm>

@{
    ViewData["Title"] = "DeleteImage";
}
 

<div>
    <div class="pagetitle">
        <h1>Xóa ảnh</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Danh sách sản phẩm</li>
                <li class="breadcrumb-item active">Xóa ảnh</li>
            </ol>
        </nav>
    </div>
    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
            @Html.ActionLink("Thêm ảnh", "AddImage", new { id = ViewBag.Id }, new {@class = "btn btn-outline-warning"})


        </div>

        <div class="card-body">
                <div class="iconslist">
       
                        @foreach (var img in Model)
                        {
                            <div class="icon">
                            <img style="
                                                width: 60px;
                                                height: 60px;
                                            " src="data:image/jpeg;base64,@(img.Data != null ? Convert.ToBase64String(img.Data) : "")"
                                 alt="File Image" />
                                <form asp-action="DeleteImage">
                                <div class="label">
                                    <label for="request.Id" >sinh tố dâu</label>
                                    <input for="request.Id" name="request.Id" type="text" value="@img.Id" hidden />
                                </div>
                            <input type="submit" value="Xóa" class="btn btn-outline-danger" />
                                </form>
                            </div>
                        }
           
        
                </div>
                </div>
    
    
   
</div>

EBook.Admin/Views/Product/Index.cshtml
@using System.Globalization
@using eBook.Utilities.Constants
@using eBook.ViewModels.Catalog.Products
@using eBook.ViewModels.Common;
@using Microsoft.AspNetCore.Http

@model ApiResult<PagedResult<ProductVm>>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setInterval(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);

        $(document).ready(function () {
            //const checkbox = document.getElementById('flexSwitchCheckDefault');
            const message = document.getElementById('mess-box');

           
            $(".form-check-input").change(function (event) {
                // Get the checked value
                const isChecked = $(this).prop('checked');
                console.log(isChecked)
                // Make an AJAX request to the controller
                const productId = $(this).attr('itemid');

                const url = `https://localhost:5001/api/products/${productId}/${isChecked}`;
                fetch(url, {
                    method: 'PUT'
                })
                    .then(response => {
                        if (response.ok) {
                            message.innerHTML = ` <div id="msgAlert" class="alert alert-success" role="alert">
                                        Cập nhật thành công
                            </div>`
                        } else {
                            
                        }
                    })
                    .catch(error => {
                        // Handle fetch error
                        // For example, display an error message or handle the error condition
                    });
            });
        });
    </script>
    
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script>
        var connection = new signalR.HubConnectionBuilder().withUrl("/productHub").build(); // Replace with the appropriate hub URL

        connection.on("SendMessage", function (product, i) {
            // Update the product list in the Index view with the new product information
            // You can use JavaScript/jQuery to update the DOM dynamically
            console.log(product,i);
        });
        connection.start().then(function () {
            console.log("Connected to the product hub.");
        }).catch(function (err) {
            console.error(err.toString(),111);
        });
    </script>

}

<div class="container-fluid">
    <h1 class="mt-4">Danh sách sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Sản phẩm</li>
        <li class="breadcrumb-item active">Danh sách sản phẩm</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                        <a class="btn btn-outline-success" asp-action="Create" asp-controller="Product">Tạo mới</a>
                </div>
                @*<div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-9">
                                    <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" style="
    border-radius: 25px;
" />
                                    <select class="form-select" name="categoryId">
                                        <option value="@ViewBag.CurrentCateId" selected disabled hidden>
                                        @(ViewBag.CurrentCateId ?? "Danh mục")
                                    </option>
                                    @foreach (var option in ViewBag.Categories)
                                    {
                                        <option value="@option.Value">@option.Text</option>
                                    }
                                </select>
                            </div>
                            <div class="cold-md-3">
                                <button type="submit" class="btn btn-primary">Tìm</button>
                                <button type="button" onclick="window.location.href='/Product/Index'" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>*@
            </div>
        </div>

        <div class="card-body">
            <div class="row" id="mess-box">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table datatable table-hover">
                    <thead>
                        <tr>
                            <th scope="col">
                                Id
                            </th>
                            <th scope="col">
                                Image
                            </th>
                            
                            <th scope="col">
                                Name
                            </th>
                            <th scope="col">
                                Original Price
                            </th>
                            <th scope="col">
                                Sale Price
                            </th>
                            <th scope="col">
                                Stock
                            </th>
                            <th scope="col">
                                Special
                            </th>
                            <th scope="col">
                                Author
                            </th>
                            <th scope="col">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ResultObj.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    <img style="
                                    width: 60px;
                                    height: 60px;
                                     " src="data:image/jpeg;base64,@(item.ThumbnailImage != null ? Convert.ToBase64String(item.ThumbnailImage) : "")" alt="File Image" />
                                </td>
                                    
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @String.Format(new CultureInfo("vi-VN"), "{0:C}",item.Price)
                                </td>
                                <td>
                                    @String.Format(new CultureInfo("vi-VN"), "{0:C}",item.OriginalPrice)

                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Stock)
                                </td>
                                <td>
                                    
                                        <div class="form-check form-switch">
                                        <input itemid="@item.Id" class="form-check-input" type="checkbox" role="switch" asp-for="@item.IsFeature" value="@item.IsFeature" id="flexSwitchCheckDefault">
                                         </div>
                                   
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Author.Name)
                                </td>
                                <td>
                                   <div>
                                        @Html.ActionLink("Sửa", "Edit", new { id = item.Id },new {@class = "btn btn-outline-primary"})
                                        @Html.ActionLink("Xem", "Detail", new { id = item.Id },new {@class = "btn btn-outline-info"})
                                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new {@class = "btn btn-outline-danger"})
                                        @Html.ActionLink("Thêm ảnh", "AddImage", new { id = item.Id }, new {@class = "btn btn-outline-warning"})
                                        @Html.ActionLink("Xóa ảnh", "DeleteImage", new { id = item.Id }, new {@class = "btn btn-outline-dark"})


                                   </div>
                                   <div class="mt-2">
                                        @Html.ActionLink("Thêm danh mục", "CategoryAssign", new { id = item.Id },new {@class = "btn btn-outline-secondary"})
                                   </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
          @*  @await Component.InvokeAsync("Pager", Model.ResultObj)*@
        </div>
    </div>
</div>
<script>
   
</script>