EBook.Admin/Controllers/CategoryController.cs
using eBook.AdminApp.Services;
using eBook.Data.Enums;
using eBook.Utilities.Constants;
using eBook.ViewModels.Catalog.Categories;
using eBook.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace eBook.AdminApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryController(
            IConfiguration configuration,
            ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
           
        }
        // GET: CategoryController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var data = await _categoryApiClient.GetAll(languageId);
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }

        // GET: CategoryController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var data = await _categoryApiClient.GetById(languageId, id);
            return View(data.ResultObj);
        }

        // GET: CategoryController/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var data = await _categoryApiClient.GetAll(languageId);
            ViewBag.ParentId = data.ResultObj.Select(x => new SelectListItem(x.Id.ToString(),x.Id.ToString(),true));
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            return View(new CategoryCreateRequest());
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _categoryApiClient.CreateCategory(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm mới danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm danh mục thất bại");
            return View(request);
        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> EditAsync(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var category = _categoryApiClient.GetById(languageId, id).Result.ResultObj;
            var editVm = new CategoryUpdateRequest()
            {
                Id = id,
                Name = category.Name,
                SeoAlias = category.SeoAlias,
                SeoDescription = category.SeoDescription,
                SeoTitle = category.SeoTitle,
                LanguageId = languageId,
                ParentId = category.ParentId,
                Status = category.Status,
                SortOrder = category.SortOrder,
            };
            var data = await _categoryApiClient.GetAll(languageId);
            ViewBag.ParentId = data.ResultObj.Select(x => new SelectListItem(x.Id.ToString(), x.Id.ToString(), true));
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            return View(editVm);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( CategoryUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _categoryApiClient.UpdateCategory(request);
            if (result>0)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật danh mục thất bại");
            return View(request);
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(new CategoryVm()
            {
                Id = id
            });
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(CategoryVm request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.DeleteCategory(request.Id);
            if (result >0)
            {
                TempData["result"] = "Xóa danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return View(request);
        }
    }
}

EBook.Admin/Controllers/Components/PagerViewComponent.cs
using eBook.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBook.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

EBook.Admin/Views/Category/Create.cshtml
@model eBook.ViewModels.Catalog.Categories.CategoryCreateRequest

@{
    ViewData["Title"] = "Create";
}

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item">Danh sách danh mục</li>
        <li class="breadcrumb-item active">Tạo mới danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input asp-for="Name" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="Description" class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <input asp-for="Description" type="text " class="form-control">
                        </div>
                        <span asp-validation-for="Description" class="text-danger"></span>

                    </div>
                   
                    <div class="row mb-3">
                        <label asp-for="SeoAlias" class="col-sm-2 col-form-label">SeoAlias</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoAlias" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="SeoTitle" class="col-sm-2 col-form-label">SeoTitle</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoTitle" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="SeoDescription" class="col-sm-2 col-form-label">SeoDescription</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoDescription" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="SortOrder" class="col-sm-2 col-form-label">SortOrder</label>
                        <div class="col-sm-10">
                            <input asp-for="SortOrder" type="number" class="form-control">
                        </div>
                        <span asp-validation-for="SortOrder" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="Status" class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                              <select asp-for="Status" asp-items="@ViewBag.Status" class="form-control"></select>

                        </div>
                        <span asp-validation-for="Status" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="ParentId" class="col-sm-2 col-form-label">ParentId</label>
                        <div class="col-sm-10">
                            <select asp-for="ParentId" asp-items="@ViewBag.ParentId" class="form-control">
                                <option value="0">None</option>
                            </select>

                        </div>
                        <span asp-validation-for="ParentId" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="LanguageId" class="col-sm-2 col-form-label">LanguageId</label>
                        <div class="col-sm-10">
                            <input asp-for="LanguageId" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="LanguageId" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-outline-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EBook.Admin/Views/Category/Delete.cshtml
@model eBook.ViewModels.Catalog.Categories.CategoryVm

@{
    ViewData["Title"] = "Delete";
}

<style>
    .table {
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        row-gap: 20px;
    }

    .term {
        width: 20%;
        display: flex;
        align-items: center;
        padding: 8px 8px;
        background-color: #1d4adf85;
        color: white;
        position: relative;
    }

        .term::after {
            content: '';
            width: 12px;
            height: 24px;
            position: absolute;
            background-color: #1d4adf85;
            left: 100%;
            clip-path: polygon(0% 0%, 100% 50%, 0% 100%);
        }

    .desc {
        width: 80%;
        background-color: #eee;
        display: flex;
        align-items: center;
        padding: 8px 8px 8px 24px;
    }

    dd {
        margin-bottom: 0px;
    }
    /* ******************************* */

    * {
        box-sizing: border-box;
        margin: 0;
    }
</style>

<div class="container-fluid">
    <h1 class="mt-4">Xóa danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách danh mục</li>

        <li class="breadcrumb-item active">Xóa danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="table">
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-outline-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

EBook.Admin/Views/Category/Details.cshtml
@model eBook.ViewModels.Catalog.Categories.CategoryVm

@{
    ViewData["Title"] = "Details";
}
<style>
    .table {
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        row-gap: 20px;
    }

    .term {
        width: 20%;
        display: flex;
        align-items: center;
        padding: 8px 8px;
        background-color: #1d4adf85;
        color: white;
        position: relative;
    }

        .term::after {
            content: '';
            width: 12px;
            height: 24px;
            position: absolute;
            background-color: #1d4adf85;
            left: 100%;
            clip-path: polygon(0% 0%, 100% 50%, 0% 100%);
        }

    .desc {
        width: 80%;
        background-color: #eee;
        display: flex;
        align-items: center;
        padding: 8px 8px 8px 24px;
    }

    dd {
        margin-bottom: 0px;
    }


    /* ******************************* */

    * {
        box-sizing: border-box;
        margin: 0;
    }
</style>



<div class="container-fluid">
    <h1 class="mt-4">Chi tiết danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách danh mục</li>

        <li class="breadcrumb-item active">Chi tiết danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-6 " style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px; padding: 10px; border-radius: 10px;width: 692px;">

                <dl class="table m-0">
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.SeoTitle)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.SeoTitle)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.SeoAlias)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.SeoAlias)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.SeoDescription)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.SeoDescription)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.ParentId)
                    </dt>
                    <dd class="desc">
                        @(Model.ParentId != null ? Model.ParentId.ToString() : "N/A")
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.SortOrder)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.SortOrder)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    <dt class="term">
                        @Html.DisplayNameFor(model => model.LanguageId)
                    </dt>
                    <dd class="desc">
                        @Html.DisplayFor(model => model.LanguageId)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

EBook.Admin/Views/Category/Edit.cshtml
@model eBook.ViewModels.Catalog.Categories.CategoryUpdateRequest

@{
    ViewData["Title"] = "Edit";
}

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item">Danh sách danh mục</li>
        <li class="breadcrumb-item active">Tạo mới danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-outline-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input asp-for="Name" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>

                    </div>
                   
                  
                    <div class="row mb-3">
                        <label asp-for="SeoAlias" class="col-sm-2 col-form-label">SeoAlias</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoAlias" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="row mb-3">
                        <label asp-for="SeoTitle" class="col-sm-2 col-form-label">SeoTitle</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoTitle" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="SeoDescription" class="col-sm-2 col-form-label">SeoDescription</label>
                        <div class="col-sm-10">
                            <input asp-for="SeoDescription" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="SortOrder" class="col-sm-2 col-form-label">SortOrder</label>
                        <div class="col-sm-10">
                            <input asp-for="SortOrder" type="number" class="form-control">
                        </div>
                        <span asp-validation-for="SortOrder" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="Status" class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                            <select asp-for="Status" asp-items="@ViewBag.Status" class="form-control"></select>

                        </div>
                        <span asp-validation-for="Status" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="ParentId" class="col-sm-2 col-form-label">ParentId</label>
                        <div class="col-sm-10">
                            <select asp-for="ParentId" asp-items="@ViewBag.ParentId" class="form-control">
                                <option value="0">None</option>
                            </select>

                        </div>
                        <span asp-validation-for="ParentId" class="text-danger"></span>

                    </div>
                    <div class="row mb-3">
                        <label asp-for="LanguageId" class="col-sm-2 col-form-label">LanguageId</label>
                        <div class="col-sm-10">
                            <input asp-for="LanguageId" type="text" class="form-control">
                        </div>
                        <span asp-validation-for="LanguageId" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-outline-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EBook.Admin/Views/Category/Index.cshtml
@model IEnumerable<eBook.ViewModels.Catalog.Categories.CategoryVm>

@{
    ViewData["Title"] = "Danh mục Sản phảm";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section Scripts{
    <script>
         setInterval(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
		var startDate = new Date("2023-06-14T12:00:00");
        console.log(startDate)
// Get the current date and time
var currentDate = new Date();

// Calculate the time difference in milliseconds
var timeDiff = currentDate - startDate;

// Calculate the elapsed time in seconds, minutes, hours, and days
var seconds = Math.floor(timeDiff / 1000);
var minutes = Math.floor(seconds / 60);
var hours = Math.floor(minutes / 60);
var days = Math.floor(hours / 24);

// Output the elapsed time
console.log("Time ago: " + days + " days, " + hours % 24 + " hours, " + minutes % 60 + " minutes, " + seconds % 60 + " seconds.");
    </script>
}

    <div class="container-fluid">
        <div class="pagetitle">
            <h1>Danh mục sản phẩm</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Sản phẩm</li>
                    <li class="breadcrumb-item active">Danh mục sản phẩm</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <div class="card mb-12">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <a class="btn btn-outline-success" asp-action="Create" asp-controller="Category">Tạo mới</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table datatable table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">SeoDescription</th>
                            <th scope="col">SeoTitle</th>
                            <th scope="col">SeoAlias</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr class="table-row">
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.SeoDescription)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.SeoTitle)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.SeoAlias)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td class="table-data">
                                    @Html.ActionLink("Edit", "Edit", new {  id = item.Id  }, new {@class = "btn btn-outline-primary"})
                                    @Html.ActionLink("Details", "Details", new { id = item.Id },new {@class = "btn btn-outline-info"})
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new {@class = "btn btn-outline-danger"})
                                </td>
                            </tr>
                        }

                    </tbody>
                    @*  @await Component.InvokeAsync("Pager", Model)*@
                </table>
            </div>
        </div>

        </div>

</div>